[package]
name = "douconel"
version = "0.0.1"
edition = "2021"

[dependencies]
potpoursi = { path = "../potpoursi" }
rand = "0.8.5"
glam = "0.24.2"
serde = "1.0.196"
itertools = "0.12.1"
simple-error = "0.3.0"
slotmap = { version = "1.0.7", features = ["serde"] }
bimap = "0.6.3"
priq = "0.1.0"

stl_io = "0.7.0"
petgraph = "0.6.4"
bevy_render = "0.12.1"