[package]
name = "douconel"
version = "0.0.1"
edition = "2021"

[dependencies]
itertools = "0.11.0"
serde = "1.0.193"
glam = { version = "0.25.0", features = ["serde"] }
simple-error = "0.3.0"

slotmap = { version = "1.0.7", features = ["serde"] }
stl_io = "0.7.0"
